# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'gmm117'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-163424282-1'

menu: 
  - name: Hong's Projects
    # submenu:
    #   - name: Hong's Projects
    #     link: /projects/gmm117
    submenu:
      - name: Portfolio
        link: https://gmm117.github.io/hong-portfolio/
      - name: Light Markdown
        link: https://gmm117.github.io/light-mkeditor/
      - name: Todo List
        link: https://gmm117.github.io/todo-tasks/
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/gmm117
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/승아-홍-7140991a6
    
